In [4]:
import numpy as np

### Creating Simples One-Dimensional Numpy Arrays

1. Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?

In [3]:
arr = np.arange(10, 101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

2. How could you create the same NumPy array using a Python range and a list?

arr_temp = [i for i in range(10, 101, 10)]
arr = np.array(arr_temp)
arr

3. What happens if you pass no arguments to the np.array()?

In [7]:
# arr = np.array()

Levanta uma exceção 'TypeError' pela falta de um objeto.

4. How might you create a NumPy array of the capital letters, A-Z?

In [9]:
from string import ascii_uppercase

capital_letters = np.array(list(ascii_uppercase))

capital_letters

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

5. How would you create a ten-element NumPy array object of all zeros?

In [10]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

6. How would you find the data type given in #5.

7. What is the data type for #5?

Para encontrar o tipo de dado do arr0, basta utilizar o atributo 'dtype' do array numpy

In [11]:
arr0.dtype

dtype('float64')

8. What function would return the same number of elements, but of all ones?

In [12]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

9. How could you create a ten-element array of random integers between 1 and 5 (inclusive)?

In [14]:
array_r = np.random.randint(1, 6, 10)
array_r

array([1, 1, 3, 2, 3, 3, 5, 2, 1, 4])

10. How can you create a normal distribution of 10 numbers, centered on 5?

In [27]:
arr = np.random.normal(5, 1, 10)
arr

array([4.45758323, 3.80892265, 6.99910252, 5.6074085 , 5.07407935,
       5.11117931, 3.68236793, 3.41500966, 7.46298665, 5.67220515])

11. What code would create an array of 10 random numbers between zero and one?

In [34]:
arr01 = np.random.rand(10)
arr01

array([9.18411512e-01, 3.19474212e-01, 8.63160475e-01, 5.42289907e-01,
       3.11160380e-05, 5.52200094e-01, 4.35116417e-01, 5.48345081e-01,
       6.65703840e-01, 1.33037343e-01])

### Creating and Using Multidimensional Arrays

12. Consider the code: np.ones((3,5)). Does this A) create an array of three arrays containing five elements each or B) create an array of five arrays containing three elements each?

In [5]:
arr = np.ones((3, 5))
arr # LETRA A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

13. Consider an array named “myarray” that is displayed as in the block below. What value does the code myarray[1,2] return? A) 10 B) 7.

In [9]:
# myarray:

myarray = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

myarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# myarray[1, 2] retorna 7

14. Given myarray as shown above, what is the value of myarray.ndim?

In [11]:
myarray.ndim

2

15. An array of three arrays of four elements each like this has twelve elements, of course. How could you create a new array consisting of two arrays of six elements each?

In [12]:
arr = np.arange(12).reshape((2, 6))

arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

17. How could you create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10?

In [16]:
arr = np.random.randint(1, 11, (3, 4))
arr

array([[ 9,  5,  4,  8],
       [ 8,  9, 10,  8],
       [ 1,  3,  5,  4]])

21. Given an array, named "arr”, that looks like:

In [17]:
# [[0, 1, 2],
# [3, 4, 5]]

How could you display an array that looks like:

In [18]:
# [[0, 3],
#  [1, 4],
#  [2, 5]]

In [23]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### Indexing and Slicing Two-Dimensional Arrays

four_by_five = np.arange(1, 21).reshape((4, 5))

four_by_five

Write a statement that prints the first row. (It will be a five-element array).

In [26]:
four_by_five[0, :]

array([1, 2, 3, 4, 5])

Write an expression to print the last row. (It will be a five-element array).

In [27]:
four_by_five[3, :]

array([16, 17, 18, 19, 20])

What does print(four_by_five[2,3]) display?

In [29]:
# print(four_by_five[2,3]) >> 14

How could you display the first column? It will be a (four-element array ending with 16.)

In [31]:
four_by_five[:, 0]

array([ 1,  6, 11, 16])

Write an expression to return the last two columns of the middle two rows.

In [33]:
four_by_five[1:3, 3:]

array([[ 9, 10],
       [14, 15]])