In [2]:
import numpy as np

### Creating Simples One-Dimensional Numpy Arrays

1. Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?

In [3]:
arr = np.arange(10, 101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

2. How could you create the same NumPy array using a Python range and a list?

arr_temp = [i for i in range(10, 101, 10)]
arr = np.array(arr_temp)
arr

3. What happens if you pass no arguments to the np.array()?

In [7]:
# arr = np.array()

Levanta uma exceção 'TypeError' pela falta de um objeto.

4. How might you create a NumPy array of the capital letters, A-Z?

In [9]:
from string import ascii_uppercase

capital_letters = np.array(list(ascii_uppercase))

capital_letters

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

5. How would you create a ten-element NumPy array object of all zeros?

In [10]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

6. How would you find the data type given in #5.

7. What is the data type for #5?

Para encontrar o tipo de dado do arr0, basta utilizar o atributo 'dtype' do array numpy

In [11]:
arr0.dtype

dtype('float64')

8. What function would return the same number of elements, but of all ones?

In [12]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

9. How could you create a ten-element array of random integers between 1 and 5 (inclusive)?

In [14]:
array_r = np.random.randint(1, 6, 10)
array_r

array([1, 1, 3, 2, 3, 3, 5, 2, 1, 4])

10. How can you create a normal distribution of 10 numbers, centered on 5?

In [27]:
arr = np.random.normal(5, 1, 10)
arr

array([4.45758323, 3.80892265, 6.99910252, 5.6074085 , 5.07407935,
       5.11117931, 3.68236793, 3.41500966, 7.46298665, 5.67220515])

11. What code would create an array of 10 random numbers between zero and one?

In [34]:
arr01 = np.random.rand(10)
arr01

array([9.18411512e-01, 3.19474212e-01, 8.63160475e-01, 5.42289907e-01,
       3.11160380e-05, 5.52200094e-01, 4.35116417e-01, 5.48345081e-01,
       6.65703840e-01, 1.33037343e-01])

### Creating and Using Multidimensional Arrays